version: '2'
services:
  gc:
    image: spotify/docker-gc
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc:/etc:ro
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.scheduler.global: 'true'
      cron.schedule: '0 * * * * ?'
